FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat openssl && \
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.16/main" >> /etc/apk/repositories && \
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.16/community" >> /etc/apk/repositories && \
    apk add --no-cache libssl1.1
WORKDIR /app

FROM base AS deps
COPY package*.json ./
RUN npm install --no-audit --no-fund --loglevel info --ignore-scripts

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate || true
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "start"]
