FROM node:20-bullseye-slim
WORKDIR /app

# Install openssl for Prisma
RUN apt-get update && apt-get install -y openssl curl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install --loglevel verbose

COPY . .

# Generate prisma client
RUN npx prisma generate

ENV NODE_ENV=production

# Expose Bull board port
EXPOSE 4501

CMD ["npx", "tsx", "scripts/start-worker.ts"]
