
const fs = require('fs');
const content = `DB_SERVER=162.55.212.193,14315
DB_NAME=PICKPIC
DB_USER=sa
DB_PASSWORD=V3r!fy#92uM@xTq1zR71

# Firebase Config (Legacy/Hybrid)
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
`;

fs.writeFileSync('.env', content);
console.log('.env updated via Node');
