/*
PickPic Production Schema Script
Generated by Antigravity
Target: SQL Server 2019+
*/

-- 1. Create Database
IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'PickPic')
BEGIN
    CREATE DATABASE PickPic;
END
GO

USE PickPic;
GO

-- 2. Create Schemas
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'auth') EXEC('CREATE SCHEMA [auth]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'marketplace') EXEC('CREATE SCHEMA [marketplace]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'ai') EXEC('CREATE SCHEMA [ai]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'audit') EXEC('CREATE SCHEMA [audit]');
GO

-- 3. Tables & Constraints

-- =============================================
-- AUTH SCHEMA
-- =============================================

-- auth.Users
IF OBJECT_ID('auth.Users', 'U') IS NULL
BEGIN
    CREATE TABLE auth.Users (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        email NVARCHAR(320) NOT NULL,
        password_hash VARBINARY(MAX) NULL, -- Nullable for OAuth
        display_name NVARCHAR(120) NULL,
        phone NVARCHAR(30) NULL,
        is_active BIT NOT NULL DEFAULT 1,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_Users_Email UNIQUE(email)
    );
END
GO

-- auth.Roles
IF OBJECT_ID('auth.Roles', 'U') IS NULL
BEGIN
    CREATE TABLE auth.Roles (
        id INT IDENTITY(1,1) PRIMARY KEY,
        name NVARCHAR(50) NOT NULL,
        CONSTRAINT UQ_Roles_Name UNIQUE(name)
    );
END
GO

-- auth.UserRoles
IF OBJECT_ID('auth.UserRoles', 'U') IS NULL
BEGIN
    CREATE TABLE auth.UserRoles (
        user_id UNIQUEIDENTIFIER NOT NULL,
        role_id INT NOT NULL,
        assigned_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT PK_UserRoles PRIMARY KEY (user_id, role_id),
        CONSTRAINT FK_UserRoles_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE CASCADE,
        CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (role_id) REFERENCES auth.Roles(id) ON DELETE CASCADE
    );
END
GO

-- =============================================
-- MARKETPLACE SCHEMA
-- =============================================

-- marketplace.SellerProfiles
IF OBJECT_ID('marketplace.SellerProfiles', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.SellerProfiles (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        user_id UNIQUEIDENTIFIER NOT NULL,
        store_name NVARCHAR(100) NOT NULL,
        bio NVARCHAR(1000) NULL,
        location_lat DECIMAL(9,6) NULL,
        location_lng DECIMAL(9,6) NULL,
        location_geohash NVARCHAR(16) NULL,
        location_precision NVARCHAR(40) NULL, -- e.g. 'City', 'Neighborhood'
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_SellerProfiles_UserId UNIQUE(user_id),
        CONSTRAINT FK_SellerProfiles_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION -- Don't delete profile automatically if user has history? Or Cascade? 'Restricted' implies NO ACTION or check.
    );
    -- Index for geo queries
    CREATE INDEX IX_SellerProfiles_Geohash ON marketplace.SellerProfiles(location_geohash);
END
GO

-- marketplace.Products
IF OBJECT_ID('marketplace.Products', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Products (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        seller_id UNIQUEIDENTIFIER NOT NULL,
        title NVARCHAR(200) NOT NULL,
        description NVARCHAR(MAX) NULL,
        category NVARCHAR(100) NULL,
        condition NVARCHAR(50) NULL, -- e.g., 'New', 'Used'
        price DECIMAL(18,2) NOT NULL,
        currency CHAR(3) NOT NULL DEFAULT 'USD',
        status NVARCHAR(20) NOT NULL DEFAULT 'draft', -- draft, published, sold, archived
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_Products_SellerProfiles FOREIGN KEY (seller_id) REFERENCES marketplace.SellerProfiles(id) ON DELETE NO ACTION, -- Don't delete products if seller deleted? Safer.
        CONSTRAINT CHK_Products_Status CHECK (status IN ('draft', 'published', 'sold', 'archived'))
    );
    CREATE INDEX IX_Products_SellerId ON marketplace.Products(seller_id);
    CREATE INDEX IX_Products_Category ON marketplace.Products(category) WHERE status = 'published';
    CREATE INDEX IX_Products_Status ON marketplace.Products(status);
END
GO

-- marketplace.ProductImages
IF OBJECT_ID('marketplace.ProductImages', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.ProductImages (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_id UNIQUEIDENTIFIER NOT NULL,
        image_url NVARCHAR(2048) NOT NULL,
        blurhash NVARCHAR(128) NULL,
        width INT NULL,
        height INT NULL,
        mime_type NVARCHAR(50) NULL,
        is_primary BIT NOT NULL DEFAULT 0,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ProductImages_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_ProductImages_ProductId ON marketplace.ProductImages(product_id);
    CREATE INDEX IX_ProductImages_Primary ON marketplace.ProductImages(product_id) WHERE is_primary = 1;
END
GO

-- marketplace.ProductAttributes
IF OBJECT_ID('marketplace.ProductAttributes', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.ProductAttributes (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_id UNIQUEIDENTIFIER NOT NULL,
        attributes_json NVARCHAR(MAX) NOT NULL, -- EAV stored as JSON
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ProductAttributes_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_ProductAttributes_ProductId ON marketplace.ProductAttributes(product_id);
END
GO

-- marketplace.Favorites
IF OBJECT_ID('marketplace.Favorites', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Favorites (
        user_id UNIQUEIDENTIFIER NOT NULL,
        product_id UNIQUEIDENTIFIER NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT PK_Favorites PRIMARY KEY (user_id, product_id),
        CONSTRAINT FK_Favorites_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE CASCADE, -- If user delete, favors gone
        CONSTRAINT FK_Favorites_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE -- If product gone, favor gone
    );
END
GO

-- marketplace.MessageThreads
IF OBJECT_ID('marketplace.MessageThreads', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.MessageThreads (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        buyer_user_id UNIQUEIDENTIFIER NOT NULL,
        seller_user_id UNIQUEIDENTIFIER NOT NULL,
        product_id UNIQUEIDENTIFIER NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_MessageThreads UNIQUE(buyer_user_id, seller_user_id, product_id),
        CONSTRAINT FK_MessageThreads_Buyer FOREIGN KEY (buyer_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION,
        CONSTRAINT FK_MessageThreads_Seller FOREIGN KEY (seller_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION,
        CONSTRAINT FK_MessageThreads_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_MessageThreads_Buyer ON marketplace.MessageThreads(buyer_user_id);
    CREATE INDEX IX_MessageThreads_Seller ON marketplace.MessageThreads(seller_user_id);
END
GO

-- marketplace.Messages
IF OBJECT_ID('marketplace.Messages', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Messages (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        thread_id UNIQUEIDENTIFIER NOT NULL,
        sender_user_id UNIQUEIDENTIFIER NOT NULL,
        body NVARCHAR(MAX) NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_Messages_Threads FOREIGN KEY (thread_id) REFERENCES marketplace.MessageThreads(id) ON DELETE CASCADE,
        CONSTRAINT FK_Messages_Sender FOREIGN KEY (sender_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION
    );
    CREATE INDEX IX_Messages_Thread_CreatedAt ON marketplace.Messages(thread_id, created_at);
END
GO

-- =============================================
-- AI SCHEMA
-- =============================================

-- ai.ImageEmbeddings
IF OBJECT_ID('ai.ImageEmbeddings', 'U') IS NULL
BEGIN
    CREATE TABLE ai.ImageEmbeddings (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_image_id UNIQUEIDENTIFIER NOT NULL,
        model_name NVARCHAR(100) NOT NULL,
        -- Storing vector as JSON array (e.g. '[0.1, 0.2, ...]') for compatibility.
        -- If SQL 2022+ is available/enabled later, we can add a VECTOR column.
        embedding_json NVARCHAR(MAX) NULL, 
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_ImageEmbeddings_ImageId UNIQUE(product_image_id),
        CONSTRAINT FK_ImageEmbeddings_Images FOREIGN KEY (product_image_id) REFERENCES marketplace.ProductImages(id) ON DELETE CASCADE
    );
END
GO

-- =============================================
-- AUDIT SCHEMA
-- =============================================

-- audit.SearchEvents
IF OBJECT_ID('audit.SearchEvents', 'U') IS NULL
BEGIN
    CREATE TABLE audit.SearchEvents (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        user_id UNIQUEIDENTIFIER NULL,
        query_type NVARCHAR(50) NOT NULL, -- 'visual', 'text'
        metadata_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_SearchEvents_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE SET NULL
    );
    CREATE INDEX IX_SearchEvents_CreatedAt ON audit.SearchEvents(created_at);
    CREATE INDEX IX_SearchEvents_UserId ON audit.SearchEvents(user_id);
END
GO

-- 4. Triggers for UpdatedAt

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_Users_UpdatedAt') DROP TRIGGER auth.trg_Users_UpdatedAt;
GO
CREATE TRIGGER auth.trg_Users_UpdatedAt ON auth.Users AFTER UPDATE AS
BEGIN
    UPDATE auth.Users SET updated_at = SYSDATETIME() FROM auth.Users u INNER JOIN inserted i ON u.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_SellerProfiles_UpdatedAt') DROP TRIGGER marketplace.trg_SellerProfiles_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_SellerProfiles_UpdatedAt ON marketplace.SellerProfiles AFTER UPDATE AS
BEGIN
    UPDATE marketplace.SellerProfiles SET updated_at = SYSDATETIME() FROM marketplace.SellerProfiles t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_Products_UpdatedAt') DROP TRIGGER marketplace.trg_Products_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_Products_UpdatedAt ON marketplace.Products AFTER UPDATE AS
BEGIN
    UPDATE marketplace.Products SET updated_at = SYSDATETIME() FROM marketplace.Products t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_ProductAttributes_UpdatedAt') DROP TRIGGER marketplace.trg_ProductAttributes_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_ProductAttributes_UpdatedAt ON marketplace.ProductAttributes AFTER UPDATE AS
BEGIN
    UPDATE marketplace.ProductAttributes SET updated_at = SYSDATETIME() FROM marketplace.ProductAttributes t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_MessageThreads_UpdatedAt') DROP TRIGGER marketplace.trg_MessageThreads_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_MessageThreads_UpdatedAt ON marketplace.MessageThreads AFTER UPDATE AS
BEGIN
    UPDATE marketplace.MessageThreads SET updated_at = SYSDATETIME() FROM marketplace.MessageThreads t INNER JOIN inserted i ON t.id = i.id;
END
GO

-- 5. Seed Data

-- Roles
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'buyer') INSERT INTO auth.Roles (name) VALUES ('buyer');
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'seller') INSERT INTO auth.Roles (name) VALUES ('seller');
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'admin') INSERT INTO auth.Roles (name) VALUES ('admin');

-- Admin User
DECLARE @AdminEmail NVARCHAR(320) = 'admin@pickpic.com';
IF NOT EXISTS (SELECT * FROM auth.Users WHERE email = @AdminEmail)
BEGIN
    INSERT INTO auth.Users (email, display_name, password_hash, is_active)
    VALUES (@AdminEmail, 'System Admin', 0x, 1); -- 0x dummy hash, requires actual update
    
    DECLARE @AdminId UNIQUEIDENTIFIER = (SELECT id FROM auth.Users WHERE email = @AdminEmail);
    DECLARE @AdminRoleId INT = (SELECT id FROM auth.Roles WHERE name = 'admin');
    
    INSERT INTO auth.UserRoles (user_id, role_id) VALUES (@AdminId, @AdminRoleId);
END
GO

-- =============================================
-- SUPER ADMIN EXTENSIONS
-- =============================================

-- Schema: audit (Ensure exists)
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'audit') EXEC('CREATE SCHEMA [audit]');
GO

-- Table: audit.events
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[audit].[events]') AND type in (N'U'))
BEGIN
    CREATE TABLE [audit].[events] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        actor_id UNIQUEIDENTIFIER NOT NULL, -- UUID to match auth.Users
        action VARCHAR(100) NOT NULL, 
        entity_type VARCHAR(50) NOT NULL, 
        entity_id VARCHAR(100) NULL, 
        details NVARCHAR(MAX) NULL, 
        ip_address VARCHAR(45) NULL,
        created_at DATETIME2 DEFAULT GETDATE()
    );
    CREATE INDEX IX_audit_events_actor ON [audit].[events](actor_id);
    CREATE INDEX IX_audit_events_created_at ON [audit].[events](created_at);
END
GO

-- Schema: moderation
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'moderation') EXEC('CREATE SCHEMA [moderation]');
GO

-- Table: moderation.reports
-- Check if exists, if created with INT reporter_id, we might need to alter or drop. 
-- For now, IF NOT EXISTS is safe.
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[moderation].[reports]') AND type in (N'U'))
BEGIN
    CREATE TABLE [moderation].[reports] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        reporter_id UNIQUEIDENTIFIER NOT NULL, -- UUID
        target_type VARCHAR(50) NOT NULL, 
        target_id VARCHAR(100) NOT NULL,
        reason_category VARCHAR(50) NOT NULL,
        details NVARCHAR(MAX) NULL,
        status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'REVIEWING', 'RESOLVED', 'DISMISSED')),
        resolution_notes NVARCHAR(MAX) NULL,
        resolved_by UNIQUEIDENTIFIER NULL, -- UUID
        resolved_at DATETIME2 NULL,
        created_at DATETIME2 DEFAULT GETDATE()
    );
    CREATE INDEX IX_moderation_reports_status ON [moderation].[reports](status);
END
GO

-- Schema: content
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'content') EXEC('CREATE SCHEMA [content]');
GO

-- Table: content.faq_categories
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[content].[faq_categories]') AND type in (N'U'))
BEGIN
    CREATE TABLE [content].[faq_categories] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        name NVARCHAR(100) NOT NULL,
        display_order INT DEFAULT 0,
        is_visible BIT DEFAULT 1,
        created_at DATETIME2 DEFAULT GETDATE()
    );
END
GO

-- Table: content.faq_items
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[content].[faq_items]') AND type in (N'U'))
BEGIN
    CREATE TABLE [content].[faq_items] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        category_id INT NOT NULL,
        question NVARCHAR(255) NOT NULL,
        answer NVARCHAR(MAX) NOT NULL,
        display_order INT DEFAULT 0,
        is_visible BIT DEFAULT 1,
        created_at DATETIME2 DEFAULT GETDATE(),
        FOREIGN KEY (category_id) REFERENCES [content].[faq_categories](id)
    );
END
GO

-- Schema: settings
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'settings') EXEC('CREATE SCHEMA [settings]');
GO

-- Table: settings.feature_flags
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[settings].[feature_flags]') AND type in (N'U'))
BEGIN
    CREATE TABLE [settings].[feature_flags] (
        key_name VARCHAR(100) PRIMARY KEY,
        is_enabled BIT DEFAULT 0,
        description NVARCHAR(255) NULL,
        updated_at DATETIME2 DEFAULT GETDATE(),
        updated_by UNIQUEIDENTIFIER NULL -- UUID
    );
END
GO

-- Table: settings.system_config
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[settings].[system_config]') AND type in (N'U'))
BEGIN
    CREATE TABLE [settings].[system_config] (
        key_name VARCHAR(100) PRIMARY KEY,
        value NVARCHAR(MAX) NULL,
        type VARCHAR(20) DEFAULT 'STRING', 
        description NVARCHAR(255) NULL,
        updated_at DATETIME2 DEFAULT GETDATE()
    );
END
GO

-- Schema: ai (Ensure exists)
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'ai') EXEC('CREATE SCHEMA [ai]');
GO

-- Table: ai.prompts
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ai].[prompts]') AND type in (N'U'))
BEGIN
    CREATE TABLE [ai].[prompts] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        version INT NOT NULL,
        prompt_text NVARCHAR(MAX) NOT NULL,
        is_active BIT DEFAULT 0,
        created_by UNIQUEIDENTIFIER NULL, -- UUID
        created_at DATETIME2 DEFAULT GETDATE()
    );
    CREATE UNIQUE INDEX UX_ai_prompts_name_version ON [ai].[prompts](name, version);
END
GO

-- Schema: localization
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'localization') EXEC('CREATE SCHEMA [localization]');
GO

-- Table: localization.languages
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[localization].[languages]') AND type in (N'U'))
BEGIN
    CREATE TABLE [localization].[languages] (
        code VARCHAR(10) PRIMARY KEY, 
        name NVARCHAR(50) NOT NULL,
        is_rtl BIT DEFAULT 0,
        is_active BIT DEFAULT 1
    );
END
GO

-- Table: localization.translation_keys
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[localization].[translation_keys]') AND type in (N'U'))
BEGIN
    CREATE TABLE [localization].[translation_keys] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        key_name VARCHAR(255) NOT NULL UNIQUE,
        description NVARCHAR(255) NULL
    );
END
GO

-- Table: localization.translation_values
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[localization].[translation_values]') AND type in (N'U'))
BEGIN
    CREATE TABLE [localization].[translation_values] (
        id INT IDENTITY(1,1) PRIMARY KEY,
        key_id INT NOT NULL,
        language_code VARCHAR(10) NOT NULL,
        value NVARCHAR(MAX) NOT NULL,
        FOREIGN KEY (key_id) REFERENCES [localization].[translation_keys](id),
        FOREIGN KEY (language_code) REFERENCES [localization].[languages](code)
    );
    CREATE UNIQUE INDEX UX_localization_values ON [localization].[translation_values](key_id, language_code);
END
GO

-- Seed Initial Data
IF NOT EXISTS (SELECT * FROM [settings].[feature_flags] WHERE key_name = 'maintenance_mode')
BEGIN
    INSERT INTO [settings].[feature_flags] (key_name, is_enabled, description) VALUES ('maintenance_mode', 0, 'Put the site in maintenance mode');
END

IF NOT EXISTS (SELECT * FROM [localization].[languages] WHERE code = 'en')
BEGIN
    INSERT INTO [localization].[languages] (code, name, is_rtl, is_active) VALUES ('en', 'English', 0, 1);
END
GO

-- =============================================
-- BILLING SCHEMA
-- =============================================
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'billing') EXEC('CREATE SCHEMA [billing]');
GO

IF OBJECT_ID('billing.usage_events', 'U') IS NULL
BEGIN
    CREATE TABLE billing.usage_events (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        user_id UNIQUEIDENTIFIER NULL,
        feature_name NVARCHAR(100) NOT NULL,
        metadata_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME()
    );
    CREATE INDEX IX_UsageEvents_Feature ON billing.usage_events(feature_name);
END
GO

-- =============================================
-- AI SCHEMA EXTENSIONS (Buyer Chat)
-- =============================================
IF OBJECT_ID('ai.buyer_chat_threads', 'U') IS NULL
BEGIN
    CREATE TABLE ai.buyer_chat_threads (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_id UNIQUEIDENTIFIER NOT NULL,
        user_id UNIQUEIDENTIFIER NULL, -- Null if guest
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_BuyerChatThreads_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
END
GO

IF OBJECT_ID('ai.buyer_chat_messages', 'U') IS NULL
BEGIN
    CREATE TABLE ai.buyer_chat_messages (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        thread_id UNIQUEIDENTIFIER NOT NULL,
        role NVARCHAR(20) NOT NULL, -- user, assistant
        content NVARCHAR(MAX) NOT NULL,
        citations_json NVARCHAR(MAX) NULL,
        suggested_questions_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_BuyerChatMessages_Threads FOREIGN KEY (thread_id) REFERENCES ai.buyer_chat_threads(id) ON DELETE CASCADE
    );
END
GO

IF OBJECT_ID('ai.error_log', 'U') IS NULL
BEGIN
    CREATE TABLE ai.error_log (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        service_name NVARCHAR(100) NOT NULL,
        error_message NVARCHAR(MAX) NOT NULL,
        stack_trace NVARCHAR(MAX) NULL,
        metadata_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME()
    );
END
GO

-- =============================================
-- MARKETPLACE SCHEMA EXTENSIONS (Seller Assistant)
-- =============================================
IF OBJECT_ID('marketplace.listing_assistant_sessions', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.listing_assistant_sessions (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        seller_id UNIQUEIDENTIFIER NOT NULL,
        product_id UNIQUEIDENTIFIER NOT NULL, -- Draft product
        status NVARCHAR(20) NOT NULL DEFAULT 'active', -- active, completed
        current_state_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ListingAssistant_Sellers FOREIGN KEY (seller_id) REFERENCES marketplace.SellerProfiles(id) ON DELETE NO ACTION,
        CONSTRAINT FK_ListingAssistant_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
END
GO

IF OBJECT_ID('marketplace.listing_assistant_questions', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.listing_assistant_questions (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        session_id UNIQUEIDENTIFIER NOT NULL,
        question_key NVARCHAR(100) NOT NULL,
        question_text NVARCHAR(MAX) NOT NULL,
        suggestions_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ListingAssistantQuestions_Sessions FOREIGN KEY (session_id) REFERENCES marketplace.listing_assistant_sessions(id) ON DELETE CASCADE
    );
END
GO

IF OBJECT_ID('marketplace.listing_assistant_answers', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.listing_assistant_answers (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        question_id UNIQUEIDENTIFIER NOT NULL,
        answer_text NVARCHAR(MAX) NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ListingAssistantAnswers_Questions FOREIGN KEY (question_id) REFERENCES marketplace.listing_assistant_questions(id) ON DELETE CASCADE
    );
END
GO

-- Triggers for UpdatedAt
IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_BuyerChatThreads_UpdatedAt') DROP TRIGGER ai.trg_BuyerChatThreads_UpdatedAt;
GO
CREATE TRIGGER ai.trg_BuyerChatThreads_UpdatedAt ON ai.buyer_chat_threads AFTER UPDATE AS
BEGIN
    UPDATE ai.buyer_chat_threads SET updated_at = SYSDATETIME() FROM ai.buyer_chat_threads t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_ListingAssistantSessions_UpdatedAt') DROP TRIGGER marketplace.trg_ListingAssistantSessions_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_ListingAssistantSessions_UpdatedAt ON marketplace.listing_assistant_sessions AFTER UPDATE AS
BEGIN
    UPDATE marketplace.listing_assistant_sessions SET updated_at = SYSDATETIME() FROM marketplace.listing_assistant_sessions t INNER JOIN inserted i ON t.id = i.id;
END
GO
