/*
PickPic Production Schema Script
Generated by Antigravity
Target: SQL Server 2019+
*/

-- 1. Create Database
IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'PickPic')
BEGIN
    CREATE DATABASE PickPic;
END
GO

USE PickPic;
GO

-- 2. Create Schemas
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'auth') EXEC('CREATE SCHEMA [auth]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'marketplace') EXEC('CREATE SCHEMA [marketplace]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'ai') EXEC('CREATE SCHEMA [ai]');
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'audit') EXEC('CREATE SCHEMA [audit]');
GO

-- Helper: UpdatedAt Trigger
-- We can't reuse one trigger for multiple tables easily in T-SQL without dynamic SQL, 
-- but we will define the logic to be applied via individual triggers.

-- 3. Tables & Constraints

-- =============================================
-- AUTH SCHEMA
-- =============================================

-- auth.Users
IF OBJECT_ID('auth.Users', 'U') IS NULL
BEGIN
    CREATE TABLE auth.Users (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        email NVARCHAR(320) NOT NULL,
        password_hash VARBINARY(MAX) NULL, -- Nullable for OAuth
        display_name NVARCHAR(120) NULL,
        phone NVARCHAR(30) NULL,
        is_active BIT NOT NULL DEFAULT 1,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_Users_Email UNIQUE(email)
    );
END
GO

-- auth.Roles
IF OBJECT_ID('auth.Roles', 'U') IS NULL
BEGIN
    CREATE TABLE auth.Roles (
        id INT IDENTITY(1,1) PRIMARY KEY,
        name NVARCHAR(50) NOT NULL,
        CONSTRAINT UQ_Roles_Name UNIQUE(name)
    );
END
GO

-- auth.UserRoles
IF OBJECT_ID('auth.UserRoles', 'U') IS NULL
BEGIN
    CREATE TABLE auth.UserRoles (
        user_id UNIQUEIDENTIFIER NOT NULL,
        role_id INT NOT NULL,
        assigned_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT PK_UserRoles PRIMARY KEY (user_id, role_id),
        CONSTRAINT FK_UserRoles_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE CASCADE,
        CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (role_id) REFERENCES auth.Roles(id) ON DELETE CASCADE
    );
END
GO

-- =============================================
-- MARKETPLACE SCHEMA
-- =============================================

-- marketplace.SellerProfiles
IF OBJECT_ID('marketplace.SellerProfiles', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.SellerProfiles (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        user_id UNIQUEIDENTIFIER NOT NULL,
        store_name NVARCHAR(100) NOT NULL,
        bio NVARCHAR(1000) NULL,
        location_lat DECIMAL(9,6) NULL,
        location_lng DECIMAL(9,6) NULL,
        location_geohash NVARCHAR(16) NULL,
        location_precision NVARCHAR(40) NULL, -- e.g. 'City', 'Neighborhood'
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_SellerProfiles_UserId UNIQUE(user_id),
        CONSTRAINT FK_SellerProfiles_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION -- Don't delete profile automatically if user has history? Or Cascade? 'Restricted' implies NO ACTION or check.
    );
    -- Index for geo queries
    CREATE INDEX IX_SellerProfiles_Geohash ON marketplace.SellerProfiles(location_geohash);
END
GO

-- marketplace.Products
IF OBJECT_ID('marketplace.Products', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Products (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        seller_id UNIQUEIDENTIFIER NOT NULL,
        title NVARCHAR(200) NOT NULL,
        description NVARCHAR(MAX) NULL,
        category NVARCHAR(100) NULL,
        condition NVARCHAR(50) NULL, -- e.g., 'New', 'Used'
        price DECIMAL(18,2) NOT NULL,
        currency CHAR(3) NOT NULL DEFAULT 'USD',
        status NVARCHAR(20) NOT NULL DEFAULT 'draft', -- draft, published, sold, archived
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_Products_SellerProfiles FOREIGN KEY (seller_id) REFERENCES marketplace.SellerProfiles(id) ON DELETE NO ACTION, -- Don't delete products if seller deleted? Safer.
        CONSTRAINT CHK_Products_Status CHECK (status IN ('draft', 'published', 'sold', 'archived'))
    );
    CREATE INDEX IX_Products_SellerId ON marketplace.Products(seller_id);
    CREATE INDEX IX_Products_Category ON marketplace.Products(category) WHERE status = 'published';
    CREATE INDEX IX_Products_Status ON marketplace.Products(status);
END
GO

-- marketplace.ProductImages
IF OBJECT_ID('marketplace.ProductImages', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.ProductImages (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_id UNIQUEIDENTIFIER NOT NULL,
        image_url NVARCHAR(2048) NOT NULL,
        blurhash NVARCHAR(128) NULL,
        width INT NULL,
        height INT NULL,
        mime_type NVARCHAR(50) NULL,
        is_primary BIT NOT NULL DEFAULT 0,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ProductImages_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_ProductImages_ProductId ON marketplace.ProductImages(product_id);
    CREATE INDEX IX_ProductImages_Primary ON marketplace.ProductImages(product_id) WHERE is_primary = 1;
END
GO

-- marketplace.ProductAttributes
IF OBJECT_ID('marketplace.ProductAttributes', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.ProductAttributes (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_id UNIQUEIDENTIFIER NOT NULL,
        attributes_json NVARCHAR(MAX) NOT NULL, -- EAV stored as JSON
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_ProductAttributes_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_ProductAttributes_ProductId ON marketplace.ProductAttributes(product_id);
END
GO

-- marketplace.Favorites
IF OBJECT_ID('marketplace.Favorites', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Favorites (
        user_id UNIQUEIDENTIFIER NOT NULL,
        product_id UNIQUEIDENTIFIER NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT PK_Favorites PRIMARY KEY (user_id, product_id),
        CONSTRAINT FK_Favorites_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE CASCADE, -- If user delete, favors gone
        CONSTRAINT FK_Favorites_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE -- If product gone, favor gone
    );
END
GO

-- marketplace.MessageThreads
IF OBJECT_ID('marketplace.MessageThreads', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.MessageThreads (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        buyer_user_id UNIQUEIDENTIFIER NOT NULL,
        seller_user_id UNIQUEIDENTIFIER NOT NULL,
        product_id UNIQUEIDENTIFIER NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_MessageThreads UNIQUE(buyer_user_id, seller_user_id, product_id),
        CONSTRAINT FK_MessageThreads_Buyer FOREIGN KEY (buyer_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION,
        CONSTRAINT FK_MessageThreads_Seller FOREIGN KEY (seller_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION,
        CONSTRAINT FK_MessageThreads_Products FOREIGN KEY (product_id) REFERENCES marketplace.Products(id) ON DELETE CASCADE
    );
    CREATE INDEX IX_MessageThreads_Buyer ON marketplace.MessageThreads(buyer_user_id);
    CREATE INDEX IX_MessageThreads_Seller ON marketplace.MessageThreads(seller_user_id);
END
GO

-- marketplace.Messages
IF OBJECT_ID('marketplace.Messages', 'U') IS NULL
BEGIN
    CREATE TABLE marketplace.Messages (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        thread_id UNIQUEIDENTIFIER NOT NULL,
        sender_user_id UNIQUEIDENTIFIER NOT NULL,
        body NVARCHAR(MAX) NOT NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_Messages_Threads FOREIGN KEY (thread_id) REFERENCES marketplace.MessageThreads(id) ON DELETE CASCADE,
        CONSTRAINT FK_Messages_Sender FOREIGN KEY (sender_user_id) REFERENCES auth.Users(id) ON DELETE NO ACTION
    );
    CREATE INDEX IX_Messages_Thread_CreatedAt ON marketplace.Messages(thread_id, created_at);
END
GO

-- =============================================
-- AI SCHEMA
-- =============================================

-- ai.ImageEmbeddings
IF OBJECT_ID('ai.ImageEmbeddings', 'U') IS NULL
BEGIN
    CREATE TABLE ai.ImageEmbeddings (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        product_image_id UNIQUEIDENTIFIER NOT NULL,
        model_name NVARCHAR(100) NOT NULL,
        -- Storing vector as JSON array (e.g. '[0.1, 0.2, ...]') for compatibility.
        -- If SQL 2022+ is available/enabled later, we can add a VECTOR column.
        embedding_json NVARCHAR(MAX) NULL, 
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT UQ_ImageEmbeddings_ImageId UNIQUE(product_image_id),
        CONSTRAINT FK_ImageEmbeddings_Images FOREIGN KEY (product_image_id) REFERENCES marketplace.ProductImages(id) ON DELETE CASCADE
    );
END
GO

-- =============================================
-- AUDIT SCHEMA
-- =============================================

-- audit.SearchEvents
IF OBJECT_ID('audit.SearchEvents', 'U') IS NULL
BEGIN
    CREATE TABLE audit.SearchEvents (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        user_id UNIQUEIDENTIFIER NULL,
        query_type NVARCHAR(50) NOT NULL, -- 'visual', 'text'
        metadata_json NVARCHAR(MAX) NULL,
        created_at DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_SearchEvents_Users FOREIGN KEY (user_id) REFERENCES auth.Users(id) ON DELETE SET NULL
    );
    CREATE INDEX IX_SearchEvents_CreatedAt ON audit.SearchEvents(created_at);
    CREATE INDEX IX_SearchEvents_UserId ON audit.SearchEvents(user_id);
END
GO

-- 4. Triggers for UpdatedAt

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_Users_UpdatedAt') DROP TRIGGER auth.trg_Users_UpdatedAt;
GO
CREATE TRIGGER auth.trg_Users_UpdatedAt ON auth.Users AFTER UPDATE AS
BEGIN
    UPDATE auth.Users SET updated_at = SYSDATETIME() FROM auth.Users u INNER JOIN inserted i ON u.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_SellerProfiles_UpdatedAt') DROP TRIGGER marketplace.trg_SellerProfiles_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_SellerProfiles_UpdatedAt ON marketplace.SellerProfiles AFTER UPDATE AS
BEGIN
    UPDATE marketplace.SellerProfiles SET updated_at = SYSDATETIME() FROM marketplace.SellerProfiles t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_Products_UpdatedAt') DROP TRIGGER marketplace.trg_Products_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_Products_UpdatedAt ON marketplace.Products AFTER UPDATE AS
BEGIN
    UPDATE marketplace.Products SET updated_at = SYSDATETIME() FROM marketplace.Products t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_ProductAttributes_UpdatedAt') DROP TRIGGER marketplace.trg_ProductAttributes_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_ProductAttributes_UpdatedAt ON marketplace.ProductAttributes AFTER UPDATE AS
BEGIN
    UPDATE marketplace.ProductAttributes SET updated_at = SYSDATETIME() FROM marketplace.ProductAttributes t INNER JOIN inserted i ON t.id = i.id;
END
GO

IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_MessageThreads_UpdatedAt') DROP TRIGGER marketplace.trg_MessageThreads_UpdatedAt;
GO
CREATE TRIGGER marketplace.trg_MessageThreads_UpdatedAt ON marketplace.MessageThreads AFTER UPDATE AS
BEGIN
    UPDATE marketplace.MessageThreads SET updated_at = SYSDATETIME() FROM marketplace.MessageThreads t INNER JOIN inserted i ON t.id = i.id;
END
GO

-- 5. Seed Data

-- Roles
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'buyer') INSERT INTO auth.Roles (name) VALUES ('buyer');
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'seller') INSERT INTO auth.Roles (name) VALUES ('seller');
IF NOT EXISTS (SELECT * FROM auth.Roles WHERE name = 'admin') INSERT INTO auth.Roles (name) VALUES ('admin');

-- Admin User
DECLARE @AdminEmail NVARCHAR(320) = 'admin@pickpic.com';
IF NOT EXISTS (SELECT * FROM auth.Users WHERE email = @AdminEmail)
BEGIN
    INSERT INTO auth.Users (email, display_name, password_hash, is_active)
    VALUES (@AdminEmail, 'System Admin', 0x, 1); -- 0x dummy hash, requires actual update
    
    DECLARE @AdminId UNIQUEIDENTIFIER = (SELECT id FROM auth.Users WHERE email = @AdminEmail);
    DECLARE @AdminRoleId INT = (SELECT id FROM auth.Roles WHERE name = 'admin');
    
    INSERT INTO auth.UserRoles (user_id, role_id) VALUES (@AdminId, @AdminRoleId);
END
GO

-- 6. Verification
PRINT 'Verifying Schema Creation...';

SELECT 'auth.Users' as [Table], COUNT(*) as [Count] FROM auth.Users;
SELECT 'auth.Roles' as [Table], COUNT(*) as [Count] FROM auth.Roles;
SELECT 'marketplace.Products' as [Table], COUNT(*) as [Count] FROM marketplace.Products;

-- Check Constraints
SELECT name, definition FROM sys.check_constraints;

PRINT 'Schema Production Script Completed Successfully.';
GO
